services:
  - type: web
    name: pedidos-flask
    env: python
    plan: free
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: pedidos-flask-db
          property: connectionString

databases:
  - name: pedidos-flask-db
    plan: free
